--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2024-05-18 15:18:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3363 (class 1262 OID 26373)
-- Name: dblibrarybooks; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE dblibrarybooks WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE dblibrarybooks OWNER TO postgres;

\connect dblibrarybooks

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3364 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 26476)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 26498)
-- Name: buku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buku (
    id integer NOT NULL,
    nama_buku text NOT NULL,
    jenis_buku text NOT NULL,
    penerbit text NOT NULL,
    lokasi_rak integer NOT NULL,
    stok_buku bigint NOT NULL
);


ALTER TABLE public.buku OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 26497)
-- Name: buku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 26482)
-- Name: inventori; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventori (
    id integer NOT NULL,
    nama_rak text,
    deskripsi text
);


ALTER TABLE public.inventori OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 26481)
-- Name: inventori_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventori ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventori_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 26490)
-- Name: mahasiswa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mahasiswa (
    id integer NOT NULL,
    nim_mhs text NOT NULL,
    nama_mhs text NOT NULL,
    jurusan text NOT NULL,
    aktif_flag boolean NOT NULL
);


ALTER TABLE public.mahasiswa OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 26489)
-- Name: mahasiswa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mahasiswa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mahasiswa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 26511)
-- Name: transaksi_buku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaksi_buku (
    id_buku integer NOT NULL,
    id_mhs integer NOT NULL,
    id integer NOT NULL,
    no_transaksi text NOT NULL,
    tgl_pinjam text NOT NULL,
    tgl_kembali text NOT NULL,
    lama_pinjam integer NOT NULL,
    jml_pinjam integer NOT NULL
);


ALTER TABLE public.transaksi_buku OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 26510)
-- Name: transaksi_buku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaksi_buku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaksi_buku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3349 (class 0 OID 26476)
-- Dependencies: 214
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20240518072424_InitialCreate', '8.0.5');


--
-- TOC entry 3355 (class 0 OID 26498)
-- Dependencies: 220
-- Data for Name: buku; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.buku VALUES (2, 'Bisnis Sampingan', 'Motivasi', 'Airlangga', 1, 40);
INSERT INTO public.buku VALUES (3, 'Biologi', 'Ilmiah', 'Airlangga', 1, 10);
INSERT INTO public.buku VALUES (4, 'Ensiklopedia Islam', 'Pengetahuan', 'Gramedia', 2, 30);


--
-- TOC entry 3351 (class 0 OID 26482)
-- Dependencies: 216
-- Data for Name: inventori; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.inventori VALUES (1, 'Ilmiah', 'Test');
INSERT INTO public.inventori VALUES (2, 'Ensiklopedia', 'Rak buku ensiklopedia apa saja');


--
-- TOC entry 3353 (class 0 OID 26490)
-- Dependencies: 218
-- Data for Name: mahasiswa; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.mahasiswa VALUES (1, '20240101111', 'Ben Affleck', 'Bisnis', true);


--
-- TOC entry 3357 (class 0 OID 26511)
-- Dependencies: 222
-- Data for Name: transaksi_buku; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaksi_buku VALUES (3, 1, 1, 'L4OED', '2024-05-20', '2024-06-03', 14, 2);
INSERT INTO public.transaksi_buku VALUES (2, 1, 2, 'L4OED', '2024-05-20', '2024-06-03', 14, 1);


--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 219
-- Name: buku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buku_id_seq', 4, true);


--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 215
-- Name: inventori_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventori_id_seq', 2, true);


--
-- TOC entry 3367 (class 0 OID 0)
-- Dependencies: 217
-- Name: mahasiswa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mahasiswa_id_seq', 1, true);


--
-- TOC entry 3368 (class 0 OID 0)
-- Dependencies: 221
-- Name: transaksi_buku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaksi_buku_id_seq', 2, true);


--
-- TOC entry 3193 (class 2606 OID 26480)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3200 (class 2606 OID 26504)
-- Name: buku PK_buku; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buku
    ADD CONSTRAINT "PK_buku" PRIMARY KEY (id);


--
-- TOC entry 3195 (class 2606 OID 26488)
-- Name: inventori PK_inventori; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventori
    ADD CONSTRAINT "PK_inventori" PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 26496)
-- Name: mahasiswa PK_mahasiswa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mahasiswa
    ADD CONSTRAINT "PK_mahasiswa" PRIMARY KEY (id);


--
-- TOC entry 3203 (class 2606 OID 26517)
-- Name: transaksi_buku PK_transaksi_buku; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "PK_transaksi_buku" PRIMARY KEY (id_buku, id_mhs);


--
-- TOC entry 3198 (class 1259 OID 26528)
-- Name: IX_buku_lokasi_rak; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_buku_lokasi_rak" ON public.buku USING btree (lokasi_rak);


--
-- TOC entry 3201 (class 1259 OID 26529)
-- Name: IX_transaksi_buku_id_mhs; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_transaksi_buku_id_mhs" ON public.transaksi_buku USING btree (id_mhs);


--
-- TOC entry 3204 (class 2606 OID 26505)
-- Name: buku FK_buku_inventori_lokasi_rak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buku
    ADD CONSTRAINT "FK_buku_inventori_lokasi_rak" FOREIGN KEY (lokasi_rak) REFERENCES public.inventori(id) ON DELETE CASCADE;


--
-- TOC entry 3205 (class 2606 OID 26518)
-- Name: transaksi_buku FK_transaksi_buku_buku_id_buku; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "FK_transaksi_buku_buku_id_buku" FOREIGN KEY (id_buku) REFERENCES public.buku(id) ON DELETE CASCADE;


--
-- TOC entry 3206 (class 2606 OID 26523)
-- Name: transaksi_buku FK_transaksi_buku_mahasiswa_id_mhs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "FK_transaksi_buku_mahasiswa_id_mhs" FOREIGN KEY (id_mhs) REFERENCES public.mahasiswa(id) ON DELETE CASCADE;


-- Completed on 2024-05-18 15:18:48

--
-- PostgreSQL database dump complete
--

