--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2024-05-18 12:12:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3361 (class 1262 OID 26016)
-- Name: dblibrarybooks; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE dblibrarybooks WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE dblibrarybooks OWNER TO postgres;

\connect dblibrarybooks

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3362 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 26227)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 26233)
-- Name: buku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buku (
    id integer NOT NULL,
    nama_buku text NOT NULL,
    jenis_buku text NOT NULL,
    penerbit text NOT NULL,
    lokasi_rak integer NOT NULL,
    stok_buku bigint NOT NULL
);


ALTER TABLE public.buku OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 26232)
-- Name: buku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 26241)
-- Name: inventori; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventori (
    id integer NOT NULL,
    nama_rak text,
    deskripsi text
);


ALTER TABLE public.inventori OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 26240)
-- Name: inventori_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventori ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventori_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 26249)
-- Name: mahasiswa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mahasiswa (
    id integer NOT NULL,
    nim_mhs text NOT NULL,
    nama_mhs text NOT NULL,
    jurusan text NOT NULL,
    aktif_flag boolean NOT NULL
);


ALTER TABLE public.mahasiswa OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 26248)
-- Name: mahasiswa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mahasiswa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mahasiswa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 26257)
-- Name: transaksi_buku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaksi_buku (
    id_buku integer NOT NULL,
    id_mhs integer NOT NULL,
    id integer NOT NULL,
    no_transaksi text NOT NULL,
    tgl_pinjam text NOT NULL,
    tgl_kembali text NOT NULL,
    lama_pinjam integer NOT NULL,
    jml_pinjam integer NOT NULL
);


ALTER TABLE public.transaksi_buku OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 26256)
-- Name: transaksi_buku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaksi_buku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaksi_buku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3347 (class 0 OID 26227)
-- Dependencies: 214
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20240518032350_InitialCreate', '8.0.5');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20240518033752_InitialCreate2', '8.0.5');


--
-- TOC entry 3349 (class 0 OID 26233)
-- Dependencies: 216
-- Data for Name: buku; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.buku VALUES (1, 'Biologi', 'Ilmiah', 'Airlangga', 1, 30);
INSERT INTO public.buku VALUES (2, 'Sejarah Hukum', 'Hukum', 'Gramedia', 1, 20);
INSERT INTO public.buku VALUES (3, 'Dasar Java 8', 'Teknologi Informasi', 'Gramedia', 2, 20);
INSERT INTO public.buku VALUES (4, 'Etika Bisnis', 'Bisnis', 'Airlangga', 3, 20);


--
-- TOC entry 3351 (class 0 OID 26241)
-- Dependencies: 218
-- Data for Name: inventori; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3353 (class 0 OID 26249)
-- Dependencies: 220
-- Data for Name: mahasiswa; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.mahasiswa VALUES (1, '20240101111', 'Ramdani', 'Bisnis', true);
INSERT INTO public.mahasiswa VALUES (2, '12345', 'Ben Affleck', 'MI', true);
INSERT INTO public.mahasiswa VALUES (3, '12346', 'John Cena', 'Manajemen Industri', true);
INSERT INTO public.mahasiswa VALUES (4, '12347', 'Tom', 'Hukum', true);


--
-- TOC entry 3355 (class 0 OID 26257)
-- Dependencies: 222
-- Data for Name: transaksi_buku; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaksi_buku VALUES (1, 1, 1, 'EFWQ0', '2024-05-19', '2024-05-28', 9, 1);
INSERT INTO public.transaksi_buku VALUES (3, 2, 2, 'LP4WN', '2024-05-19', '2024-06-02', 14, 2);
INSERT INTO public.transaksi_buku VALUES (4, 2, 3, 'LP4WN', '2024-05-19', '2024-06-02', 14, 1);
INSERT INTO public.transaksi_buku VALUES (2, 4, 4, 'C2KXM', '2024-05-20', '2024-05-28', 8, 1);


--
-- TOC entry 3363 (class 0 OID 0)
-- Dependencies: 215
-- Name: buku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buku_id_seq', 4, true);


--
-- TOC entry 3364 (class 0 OID 0)
-- Dependencies: 217
-- Name: inventori_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventori_id_seq', 1, false);


--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 219
-- Name: mahasiswa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mahasiswa_id_seq', 4, true);


--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 221
-- Name: transaksi_buku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaksi_buku_id_seq', 4, true);


--
-- TOC entry 3193 (class 2606 OID 26231)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3195 (class 2606 OID 26239)
-- Name: buku PK_buku; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buku
    ADD CONSTRAINT "PK_buku" PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 26247)
-- Name: inventori PK_inventori; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventori
    ADD CONSTRAINT "PK_inventori" PRIMARY KEY (id);


--
-- TOC entry 3199 (class 2606 OID 26255)
-- Name: mahasiswa PK_mahasiswa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mahasiswa
    ADD CONSTRAINT "PK_mahasiswa" PRIMARY KEY (id);


--
-- TOC entry 3202 (class 2606 OID 26263)
-- Name: transaksi_buku PK_transaksi_buku; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "PK_transaksi_buku" PRIMARY KEY (id_buku, id_mhs);


--
-- TOC entry 3200 (class 1259 OID 26274)
-- Name: IX_transaksi_buku_id_mhs; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_transaksi_buku_id_mhs" ON public.transaksi_buku USING btree (id_mhs);


--
-- TOC entry 3203 (class 2606 OID 26264)
-- Name: transaksi_buku FK_transaksi_buku_buku_id_buku; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "FK_transaksi_buku_buku_id_buku" FOREIGN KEY (id_buku) REFERENCES public.buku(id) ON DELETE CASCADE;


--
-- TOC entry 3204 (class 2606 OID 26269)
-- Name: transaksi_buku FK_transaksi_buku_mahasiswa_id_mhs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi_buku
    ADD CONSTRAINT "FK_transaksi_buku_mahasiswa_id_mhs" FOREIGN KEY (id_mhs) REFERENCES public.mahasiswa(id) ON DELETE CASCADE;


-- Completed on 2024-05-18 12:12:24

--
-- PostgreSQL database dump complete
--

